name: Build and Deploy Angular

on:
  push:
    branches:
      - master  # mainブランチにpushされたら実行

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build Angular
        run: npm run build -- --configuration production

      - name: Upload to VPS via SCP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_PRIVATE_KEY }}
          source: "dist/time-app/*"
          target: "/var/www/angular-timeApp/"